### ISSUE TITLE
Feedback on page layout

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/announcements#4]
Page: [Docs for NetApp HCI](https://docs.netapp.com/us-en/announcements/hci.html)

I find the screenshots a bit disorienting on this page. Feels a bit like a picture of a UI within the UI itself. Could this be done differently?

**Comment by netapp-bcammett** [comment]
Adam,

I changed the perspective of the screenshots so that the background shows part of the computer desktop. It creates a division between the site itself and the image. It's less disorienting that way.

https://docs.netapp.com/us-en/announcements/hci.html

Let me know what you think. 

Another option is to use the same perspective, but turn them from static GIFs to animated GIFs.

**Comment by adamn-ntap** [comment]
Thanks for making this change.  It's much better now.
